name: Build Extension
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run build
      - name: Zip Build
        # We only need to zip the contents of the `dist` directory since Vite already copies `public/` files (like manifest.json and icons) into it.
        run: cd dist && zip -r ../snapscroll-extension.zip .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapscroll-extension
          path: snapscroll-extension.zip
